name: "Run Test E2E"

on: [pull_request]

jobs:
  run-test-e2e:
    name: "Run Test E2E"
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: quriosapi
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      
      - run: npm ci
      
      - run: npm run test:e2e
        env:
          JWT_SECRET: docker
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
